### ISSUE TITLE
Cannot get it to log relationships

### ISSUE THREAD

**Issue by JayBizzle** [Neurony/laravel-revisions#5]
Hi,

Finally got round to trying out this package. Ive got it working okay for the changes on the Model, but cannot get it to log changes to relationships. I'm sure I am just missing something simple.

I have this relationship on my Model...

```php
    public function managers()
    {
        return $this->belongsToMany(User::class, 'account_managers', 'account_id', 'admin_user_id');
    }
```
...and i have setup the revision options like this...
```php
    public function getRevisionOptions(): RevisionOptions
    {
        return RevisionOptions::instance()->relationsToRevision('managers');
    }
```

The relationship gets updated like this

```php
$model->managers()->sync($data['managers'] ?? []);
```

Any thoughts on where I am going wrong?

Thanks

**Comment by zbiller** [comment]
Hi @JayBizzle 

Since you're using the `HasRevisions` trait on your other model and not on the `Manager` model, you'll need to update that model, for the revision to be triggered automatically, or you can call the `saveAsRevision()` method.

Try something like this:

```php
// just fetch your model instance
$model = Model::find($id)

// save as revision the current state of the model including the "managers" relationship
$model->saveAsRevision();
// at this point you should have an entry in the "revisions" table containing your model state, with the managers relation included

// sync your managers
$model->managers()->sync($data['managers'] ?? []);

// FOR DEBUGGING YOU CAN DO
$revision = $model->revisions()->latest()->first();

dd($revision->metadata);
// you should have a big array, but you'll be interested in the "relations" key of that array
// in there you can find your managers relation and also see what pivot entries contains (it should contain the pivots prior to your sync)
```

Hope this helps.
Please let me know if you have any questions and thanks for your interest in the package :)

**Comment by JayBizzle** [comment]
Hi @zbiller 

Thanks for your help on this but I still can't get relationships to automatically be logged.

I have two Models, `Account` and `Managers`. Both these Models are using the `HasRevisions` trait.

We are simply updating the `Account` Model like this

```php
$model->update($data);

$model->managers()->sync($data['managers'] ?? []);
```

If the data on the `Account` Model is changed, the revision gets logged, but nothing about the `managers` relation is logged 9 (if only the data on that relationship gets updated).

If I call `$model->saveAsRevision()` between the `update()` and `sync()` methods, then I will get the relationship saved (before the sync has happened), but nothing is logged when the `sync()` occurs.

Thanks again.

**Comment by zbiller** [comment]
@JayBizzle well yeah.

You're not using the trait correctly.
You should only use the `HasRevisions` trait on your `Account` model and specify the revisionable relations by using the `relationsToRevision`.

Regarding the `sync`, yes, nothing is automatically logged because `sync` doesn't trigger any Eloquent events (`updated` in this case), so to log a revision after a `sync`, just call `$model->saveAsRevision()` after the `sync` (although this is not the purpose of the revision, as the revision should contain the original data and that includes original relations data also).

Thanks!

**Comment by JayBizzle** [comment]
Thanks, it looks like i totally misunderstood how this all worked 😕 

So, for my situation, i would need to do this

```php
$model->update($data);

$model->managers()->sync($data['managers'] ?? []);

$model->saveAsRevision();
```

But i presume if `$data` has changed and also the `managers` have changed, this will log as two changes in the database?

**Comment by zbiller** [comment]
Yes, it will log 2 changes:
1. the saving of a revision triggered automatically by the `updated` Eloquent event
2. the manual call of `saveAsRevision()`
