### ISSUE TITLE
fieldsToNotRevision() method idea

### ISSUE THREAD

**Issue by RMK147** [Neurony/laravel-revisions#7]
Hello, nice package, something which I think would be useful is a method for specifying fields not to revision to compliment the fieldsToRevision() method. This would be useful when there's only one column you wish to ignore, such as an updated timestamp. Cheers!

**Comment by zbiller** [comment]
Hi @RMK147 

It's a good idea and I think it would be a nice thing to have.
I'll implement that method when I find a little time available.

Thanks for your suggestion :)

**Comment by zbiller** [comment]
Hi @RMK147 

I'm happy to let you know that excluding certain fields when creating a revision is now supported since **v3.0.1**.

Please read the [Exclude certain fields from being revisioned](https://github.com/Neurony/laravel-revisions#exclude-certain-fields-from-being-revisioned) on how to use it.
